title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          blocks:
            label: Content
            type: structure
            fields:
              text:
                label: Text
                type: writer
              illustration:
                width: 1/2
                label: Illustration
                type: files
                multiple: false
              illustration_position:
                width: 1/2
                label: Position of Illustration
                type: select
                options:
                  top: Top
                  right: Right
                  bottom: Bottom
                  left: Left

  sidebar:
    width: 1/3
    sections:
      meta:
        type: fields 
        fields:
          cover:
            type: files
            multiple: false
            layout: cards
            image:
              cover: true
      pages:
        label: Subpages
        type: pages
        template: default
