title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: writer
            size: huge
  sidebar:
    width: 1/3
    sections:
      meta:
        type: fields 
        fields:
          cover:
            type: files
            multiple: false
            layout: cards
            image:
              cover: true
      pages:
        label: Subpages
        type: pages
        template: default
