title: Site

columns:
  main:
    width: 2/3
    sections:
      artists:
        type: pages
        parent: site.children.filterBy('template', 'in', ['artists']).first
        template: artist
        layout: cards
        image:
          cover: true
      events:
        type: pages
        parent: site.children.filterBy('template', 'in', ['program']).first
        template: event
        layout: cards
        image:
          cover: true
  sidebar:
    width: 1/3
    sections:
      pages:
        label: All Pages
        type: pages
      meta:
        type: fields 
        fields:
          og_title:
            label: Page Title
            type: text
          og_description:
            label: Page Description
            type: text
          og_image:
            label: Social Media Image
            type: files
            multiple: false
      menus:
        type: fields 
        fields:
          main_menu:
            label: Main Menu
            type: pages
            fields:
              pageLink:
                type: pages
                label: Page link
                max: 1
          footer_menu:
            label: Footer Menu
            type: structure
            fields:
              linkTitle:
                type: text
                label: Menu item title
              isExternal:
                type: toggle
              pageLink:
                type: pages
                label: Page link
                max: 1
                when:
                  isExternal: false
              externalLink:
                type: url
                label: External URL
                when:
                  isExternal: true